var QuotesList = [
    'We cannot solve our problems with the same thinking we used when we created them.', 'If you want to live a happy life, tie it to a goal, not to people or objects', 'The best way to find yourself is to lose yourself in the service of others.', 'The only way to do great work is to love what you do.', "Don't let the noise of others opinions drown out your own inner voice.", "There can be no greater gift than that of giving one's time and energy to helping others without expecting anything in return.", 'A good head and a good heart are always a formidable combination.','Manungsa mung ngunduh wohing pakarti.',"Sak apik-apike wong yen awehi pitulung kanthi cara dedemitan.","Urip iku terus mlaku, bebarengan karo wektu, sing bisa gawa lakumu, supaya apik nasibmu.","Sabar iku ingaran mustikaning laku.","Aja dadi uwong sing rumangsa bisa lan rumangsa pinter. Nanging dadiya uwong sing bisa lan pinter rumangsa.","Yen urip mung isine isih nuruti nepsu, sing jenenge mulya mesti soyo angel ketemu.", "Aja mbedakake marang sak sapadha-pada.","Ngapusi kui hakmu. Kewajibanku mung etok-etok ora ngerti yen mbok apusi.","Witing tresno jalaran soko kulino. Witing mulyo jalaran wani rekoso.","Dosa sing paling menyedihkan iku dosambat ora duwe duit.","Uripmu koyo wit gedhang duwe jantung tapi ora duwe ati.","Nek dipikir suwi suwi iku loro, nek dirsake yo tambah loro, loro tambah loro, papat.","Nek ngomong ojo manis-manis, mundak cangkeme dirubung semut.","Kadang mripat iso salah ndelok, kuping iso salah krungu, lambe iso salah ngomong, tapi ati ora bakal iso diapusi.","Sing wis lunga lalekno, sing durung teko entenono, sing wis ono syukurono.","Niat kerjo, ora golek perkoro. Niat golek rejeki, ora golek rai. Ora balapan, opo maneh ugal-ugalan.","Akeh manungsa ngrasakaken tresna, tapi lalai lan ora kenal opo kui hakekate atresna.","Uwong duwe pacar iku kudu sabar ambek pasangane. Opo meneh sing gak duwe.","Ben akhire ora kecewa, dewe kudu ngerti kapan wektune berharap lan kapan wektune kudu mandeg.","Move on kuwi dudu berusaha nglalekke ya, tapi ngikhlaske lan berusaha ngentukke sing luwih apik luwih seko sing mbiyen-mbiyen.","Jarene wes ikhlas de'e karo sing liyo, kok iseh ngomong 'Nek Tuhan ra bakal mbales, karma sing mbales.' Mbok wes meneng wae luwih apik.","Mbangun kromo ingkang satuhu, boten cekap bilih ngagem sepisan roso katresnan. Hananging butuh pirang pirang katresnan lumeber ning pasangan uripmu siji kui." ];

var len = QuotesList.length;
var index = Math.floor(Math.random() * len);

var quotes = QuotesList[index]

document.getElementById("quotes").innerHTML = '"' + quotes + '"';


